### ISSUE TITLE
list variables don't do the want to be are

### ISSUE THREAD

**Issue by RosiePuddles** [RosiePuddles/fck#40]
Making a new `list` variable breaks. For some reason. Here be is the traceback:

```Python
Traceback (most recent call last):
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/shell.py", line 9, in <module>
    res = run('<shell>', text, previous)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1762, in run
    result = interpreter.visit(ast.node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1177, in visit
    return method(node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1209, in visit_ListNode
    elements.append(res.register(self.visit(element_node, context)))
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1177, in visit
    return method(node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1406, in visit_VarAssignNode
    value = res.register(node.default_value.assign_checks(value, node.pos_start, node.pos_end, context))
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/Results.py", line 19, in register
    self.error = res.error
AttributeError: 'NoneType' object has no attribute 'error'
```

Soooo.......

You know what to do. Love ya doll xxx

**Comment by RosiePuddles** [comment]
Hey doll xx
So, I had forgotten to add in the `assign_checks()` method for the list value class... anywayyyyy, added it in for the list and string. Also, going to open a new issue (enhancement), for converting between value types stolen from rust. Bye hun xx
