### ISSUE TITLE
`quit()` inside a `?` statement

### ISSUE THREAD

**Issue by RosiePuddles** [RosiePuddles/fck#46]
```py
>>> input() == 'end'? quit() :

Traceback (most recent call last):
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/shell.py", line 8, in <module>
    res = run('<shell>', text, previous)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1820, in run
    result = interpreter.visit(ast.node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1217, in visit
    return method(node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1249, in visit_ListNode
    elements.append(res.register(self.visit(element_node, context)))
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1217, in visit
    return method(node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1258, in visit_TrueFalseNode
    condition = res.register(self.visit(node.condition, context)).is_true()
AttributeError: 'NoneType' object has no attribute 'is_true'
```

i don't even know what's happening I'm just going to go write docs

**Comment by RosiePuddles** [comment]
This is not to do with the `quit()` method. It's to do with the return value of evaluating `input() == 'end'`

**Comment by RosiePuddles** [comment]
`String` class doesn't have any comparison methods. Inherited from `Value` class which just returned an error
