### ISSUE TITLE
List reassignment throws an AttributeError

### ISSUE THREAD

**Issue by RosiePuddles** [RosiePuddles/fck#6]
fck you
```
Traceback (most recent call last):
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/shell.py", line 6, in <module>
    res, error = fck_main.run('<shell>', text)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1284, in run
    result = interpreter.visit(ast.node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 909, in visit
    return method(node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 931, in visit_ListNode
    elements.append(res.register(self.visit(element_node, context)))
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 909, in visit
    return method(node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1045, in visit_VarReassignNode
    return self.visit_VarAssignNode(node, context)
  File "/Users/rosiegbartlett/Documents/Code/.fck/source/fck/PythonShell/fck_main.py", line 1018, in visit_VarAssignNode
    class_type = {'int': Int, 'float': Float, 'bool': Bool, 'list': List}.get(node.var_type)
AttributeError: 'VarReassignNode' object has no attribute 'var_type'
```

**Comment by RosiePuddles** [comment]
So, it's not just lists. Something done fucked up **BADLY**
Now no variable reassignment works
